# Generated by Django 2.1.7 on 2019-03-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try_first', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
